name: Run Pipeline on Push

on:
  push:
    branches:
      - main

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./project/requirements.txt 
  

      - name: Set execute permissions and run pipeline
        run: |
          cd project
          chmod +x pipeline.sh
          ./pipeline.sh
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      # store output files in the data folder
      - name: Upload output files
        uses: actions/upload-artifact@v2
        with:
          name: output-files
          path: ./data/*.sqlite
