name: Run Pipeline on Push

on:
  push:
    branches:
      - main

jobs:
  execute-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Set execute permissions for pipeline.sh
        run: |
          chmod +x ./project/pipeline.sh

      - name: Run pipeline
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          ./project/pipeline.sh
